### ISSUE TITLE
Questions regarding structure and abstraction

### ISSUE THREAD

**Issue by S1ri0S** [PeoplePerHour/candidate-tests#12]
I have a few things in mind that need clarification:

- Regarding **SQL injection and escaping user input**, this is mostly a platform-specific issue as differents RDBMSs may have different styles of quoting/escaping strings. Should this be an abstraction at the driver level or do I need to provide concrete implementation?

- Regarding **query caching** I have a similar question. To my mind, caching should also be an abstraction and the concrete implementation should be left to specific cache providers that will effectively function as wrappers over specific cache implementations (php-apc, Memcached, etc). Is that correct?

- I know you said we should not over-engineer things but **pagination** can be a tricky subject (especially with _*-to-many_ relationships between tables). Would limit/skip parameters in a select method be enough or do I need to provide a more structured solution like a full-blown Paginator?

Thanks.

**Comment by tavantzo** [comment]
@S1ri0S Hi Giorgos,

1. Regarding SQL Injection: We would definitely need that in the abstraction layer just because it varies from platform to platform. If you provide a concrete Database Driver, then Yes it should have been implemented properly.

2. For query caching, there should be an abstraction layer as well, for the same reason as above, and I would recommend that the implementation should be as an addon of the Database manager and NOT bundled in the RDBMS abstraction layer.

3. Regarding pagination: Some platforms using LIMIT..OFFSET, Oracle uses the `ROWNUM`, M$-SQL uses `TOP`, so as above this MUST be in the abstraction layer, so implemented properly by every database driver class.

PS: Please note that it's not needed for you to provide a driver for every RDBMS. You just need to provide a DB manager  - that would be able to use these database drivers  - and an abstract class or interface, that describes the RDBMS abstraction layer.

Kindly Regards
