### ISSUE TITLE
Which type ?

### ISSUE THREAD

**Issue by tsirigotis** [PeoplePerHour/candidate-tests#3]
[here ](https://www.xaprb.com/blog/2006/08/13/four-types-of-database-abstraction-layers/)we can find the basic tyoe of DB absctractions from what i can understand you require a concrete implementation of type 2  (DatabaseManager) ,that depends upon an absctact type  1  . Is that correct ?

**Comment by tavantzo** [comment]
@tsirigotis Yes, the 2nd seems the most suitable way to go while the 1st doesn't seem relevant.
The `DatabaseManager` should handle the database specific driver libraries that implement a certain abstraction layer, in order to connect and execute queries.

I don't know if i've answered your question.

**Comment by tsirigotis** [comment]
Thank you 
another question: 
should we implement create a some implementations of the 

> DataBase 

interface ?

**Comment by tavantzo** [comment]
@tsirigotis No it's not required but if feel that you should implement one, just keep it as minimal as you can.

**Comment by tsirigotis** [comment]
thanks !
